version: "3"
services:
  xmas2021-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Start123!
      POSTGRES_DB: xmas2021
    ports:
      - 5432:5432
    networks:
      - xmas2021

networks:
  xmas2021:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"

