version: "3"
services:
  xmas2021-frontend:
    build: 
      context: ./front/
      dockerfile: ./DOCKERFILE 
    restart: always
    networks:
      - xmas2021-proxy
      - xmas2021

  xmas2021-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Start123!
      POSTGRES_DB: xmas2021
    networks:
      - xmas2021

  xmas2021-api:
    build:
      context: ./backend/
      dockerfile: ./DOCKERFILE
    restart: always
    networks:
      - xmas2021-proxy
      - xmas2021

networks:
  xmas2021-proxy:
    external:
      name: proxy_xmas2021
  xmas2021:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"

