version: "3"
services:
  xmas2021-frontend:
    build: 
      context: .
      dockerfile: ./DOCKERFILE 
    restart: always
    networks:
      - xmas2021-proxy
      - xmas2021

networks:
  xmas2021-proxy:
    external:
      name: proxy_xmas2021
  xmas2021:
    external:
      name: emilie_xmas_xmas2021 
